# ML Playground 00 - Understanding the Dataset

Goal:
Learn how to inspect a dataset before building any machine learning model.

Questions:
- What is a dataset?
- What is a row?
- What is a column?
- What is a feature?
- What is a label?
- What kinds of data do we have?

In [2]:
from pathlib import Path
import pandas as pd

project_root = Path(r"D:\ml internship\applied-search-ml")
data_path = project_root / "data" / "raw" / "content_refresh_anonymized.csv"

print(data_path)
df = pd.read_csv(data_path)
df.head()

D:\ml internship\applied-search-ml\data\raw\content_refresh_anonymized.csv

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.head

<bound method NDFrame.head of                  content_id          client_id  search_volume  competition  \
0      content_304f48230142  client_f369cb89fc           10.0         0.67
1      content_a1fb4e703a9e  client_4e07408562           90.0         0.01
2      content_9aa793d4d895  client_7f2253d7e2            0.0         0.00
3      content_331d6c4de07b  client_19581e27de           10.0         0.00
4      content_d99b7a2d90ca  client_3fdba35f04            0.0         0.00
...                     ...                ...            ...          ...
29995  content_c322796023c8  client_e29c9c180c           10.0         0.05
29996  content_526572edb3fa  client_7f2253d7e2            0.0         0.00
29997  content_38112bdd0c6e  client_349c41201b           10.0         1.00
29998  content_ab26273a7e7a  client_19581e27de           10.0         0.00
29999  content_887020f20b5e  client_6208ef0f77            0.0         0.00

      competition_level   cpc     content_type    main_intent  word_count  \
0                  HIGH  2.05  keyword article  transactional      3221.0
1                   LOW  0.05  keyword article  informational      2481.0
2                   LOW  0.00  keyword article  informational      3515.0
3                   LOW  0.00  keyword article     commercial         NaN
4                   LOW  0.00  keyword article  informational      2803.0
...                 ...   ...              ...            ...         ...
29995               LOW  0.00  keyword article  transactional      1386.0
29996               LOW  0.00  keyword article  informational      2654.0
29997              HIGH  0.00  keyword article  transactional      2857.0
29998               LOW  0.00  keyword article  transactional         NaN
29999               LOW  0.00  keyword article     commercial      4124.0

       char_count  ... char_count_tier   ctr  avg_position  engagement_rate  \
0         20457.0  ...     15000-25000  0.76          10.6             5.88
1         15562.0  ...     15000-25000  0.05          20.3             0.00
2         23643.0  ...     15000-25000  0.09          36.5             0.00
3             NaN  ...             NaN  0.49           6.2             1.28
4         17469.0  ...     15000-25000  0.13          44.0             0.00
...           ...  ...             ...   ...           ...              ...
29995      9084.0  ...      8000-15000  0.00           0.0             0.00
29996     17056.0  ...     15000-25000  0.39           6.6             0.00
29997     18725.0  ...     15000-25000  0.19           4.1             0.00
29998         NaN  ...             NaN  0.22           6.0             1.73
29999     26315.0  ...          25000+  1.89           8.4             6.58

       scroll_rate  ai_traffic_pct  impression_tier  position_tier  \
0             4.55            0.00             good       striking
1            10.00            0.00             good       page_3_5
2            28.57            0.00             good       page_3_5
3             3.45            0.00             good         page_1
4            24.29            0.00             good       page_3_5
...            ...             ...              ...            ...
29995         0.00            0.00              low          top_3
29996        66.67            0.00         moderate         page_1
29997         0.00            0.00             good         page_1
29998         4.06            0.00        excellent         page_1
29999         3.31            2.63             good         page_1

       trend_direction  trend_pct
0                 down      -41.4
1                 down      -57.7
2                 down      -60.9
3               stable      -13.8
4                 down      -34.7
...                ...        ...
29995              new        NaN
29996             down      -75.1
29997             down      -66.2
29998             down      -27.9
29999           stable       12.3

[30000 rows x 44 columns]>

In [5]:
df.shape

(30000, 44)

In [6]:
len(df)

30000

In [7]:
df.columns

Index(['content_id', 'client_id', 'search_volume', 'competition',
       'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count',
       'char_count', 'provider_used', 'model_used', 'impressions_90d',
       'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d',
       'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d',
       'days_with_impressions', 'days_with_sessions', 'impressions_last_30d',
       'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d',
       'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier',
       'age_tier_order', 'days_since_last_update', 'freshness_tier',
       'word_count_tier', 'char_count_tier', 'ctr', 'avg_position',
       'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier',
       'position_tier', 'trend_direction', 'trend_pct'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  str
 1   client_id               30000 non-null  str
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  str
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  str
 7   main_intent             27626 non-null  str
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   str
 11  model_used              24267 non-null  str
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  str
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  str
 33  word_count_tier         22301 non-null  str
 34  char_count_tier         22301 non-null  str
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  str
 41  position_tier           30000 non-null  str
 42  trend_direction         30000 non-null  str
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), str(14)
memory usage: 10.1 MB

In [9]:
df.mean(numeric_only=True)

search_volume               158.882391
competition                   0.146954
cpc                           0.485342
word_count                 3107.760325
char_count                20665.277835
impressions_90d            5200.366300
clicks_90d                   16.097333
pageviews_90d                49.942467
sessions_90d                 37.066633
users_90d                    35.937700
engaged_sessions_90d          0.991933
ai_sessions_90d               0.204500
scroll_events_90d             4.033500
days_with_impressions        61.454033
days_with_sessions           13.096333
impressions_last_30d       1429.058733
clicks_last_30d               4.933867
sessions_last_30d            14.114267
impressions_prev_30d       1783.078500
clicks_prev_30d               5.435100
sessions_prev_30d            10.283000
content_age_days            256.167800
age_tier_order                4.786533
days_since_last_update       46.098300
ctr                           0.510733
avg_position                 16.342380
engagement_rate               2.534520
scroll_rate                  18.212921
ai_traffic_pct                0.768196
trend_pct                    -4.785969
dtype: float64

In [10]:
df.dtypes

content_id                    str
client_id                     str
search_volume             float64
competition               float64
competition_level             str
cpc                       float64
content_type                  str
main_intent                   str
word_count                float64
char_count                float64
provider_used                 str
model_used                    str
impressions_90d             int64
clicks_90d                  int64
pageviews_90d               int64
sessions_90d                int64
users_90d                   int64
engaged_sessions_90d        int64
ai_sessions_90d             int64
scroll_events_90d           int64
days_with_impressions       int64
days_with_sessions          int64
impressions_last_30d        int64
clicks_last_30d             int64
sessions_last_30d           int64
impressions_prev_30d        int64
clicks_prev_30d             int64
sessions_prev_30d           int64
content_age_days            int64
age_tier                      str
age_tier_order              int64
days_since_last_update      int64
freshness_tier                str
word_count_tier               str
char_count_tier               str
ctr                       float64
avg_position              float64
engagement_rate           float64
scroll_rate               float64
ai_traffic_pct            float64
impression_tier               str
position_tier                 str
trend_direction               str
trend_pct                 float64
dtype: object

## Rule #1

Not every column should become a feature.

A good feature gives useful information about the target.

An ID usually doesn't help because it only identifies a record.

A leaked column is even worse because it already contains the answer we are trying to predict.

In [11]:
[col for col in ["trend_direction", "trend_pct", "is_declining_label"] if col in df.columns]

['trend_direction', 'trend_pct']

In [12]:
df[["trend_direction", "trend_pct"]].head()

  trend_direction  trend_pct
0            down      -41.4
1            down      -57.7
2            down      -60.9
3          stable      -13.8
4            down      -34.7

# High level Ml Pipeline
    Business Problem
            ↓
    Collect historical data
            ↓
    Clean the data
            ↓
    Choose useful features
            ↓
    Create labels
            ↓
    Split train/test
            ↓
    Train a model
            ↓
    Evaluate it
            ↓
    Deploy it on completely new data